"""i101: does the model pass the gameweek a /fixtures cell tap names, and
does the produced answer describe THAT gameweek?

MEASUREMENT ONLY -- real, paid LLM calls through the SAME ``run_one`` the
tool-routing / i82 / i78-A measurements used (measure_tool_routing.py: pinned
provider/model, same observation row, same cost table). Nothing is mocked
and nothing product-side is edited.

Why a sibling of measure_i78a_fixture_click_routing.py and not a flag on it:
i78-A measured WHICH tool the model picks; it never looked at the arguments,
so a cell tap on J5 answered with J4 read as a hit there. This script keeps
the same corpus contract (the phrases are generated by the jest test from the
UI's own functions) but selects only the cells at least ``--min-lead`` GWs
past the bootstrap's current GW -- the case where guessing ``horizon=1`` is
invisible-wrong -- and records, per executed tool call:

* ``args.target_gw``       -- did the literal number in the text arrive?
* ``output.series[].gameweek`` -- which gameweek did the tool describe?
* ``args.horizon``         -- was the old arithmetic still attempted?

so the read-out (analyze_i101_target_gw_args.py) compares each against the
generator's ``gameweek`` metadata, never against the prose of the question.

Current GW is resolved from the bootstrap with the engine's own resolver and
stamped on every row; the lead of each phrase is computed from it. Fixed
order, ``--reps`` back to back, JSONL flushed after every call.

Usage (from packages/fpl-grounded-assistant; .env is read for the API key):
    python scripts/measure_i101_target_gw_args.py \
        --out field-notes/artifacts/i101-target-gw-before.jsonl --reps 3
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import measure_tool_routing as base  # noqa: E402

#: The tool whose arguments this measurement is about.
TOOL = "get_fixture_outlook"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _estimate_usd(n_calls: int) -> float:
    # i78-A measured 114 calls at $0.1008 on the same model and corpus shape.
    return round(n_calls * (0.1008 / 114), 3)


def _series_gws(output: Any) -> list[int]:
    if not isinstance(output, dict):
        return []
    out: list[int] = []
    for entry in output.get("series") or []:
        try:
            out.append(int(entry.get("gameweek")))
        except (TypeError, ValueError, AttributeError):
            continue
    return out


class _ResultCapture:
    """Wraps ``ask_orchestrated`` so the per-call trace (args + output) of the
    result object is available to this script; ``run_one`` only projects the
    retained tool's args and the output status."""

    def __init__(self) -> None:
        self.last: Any = None

    def wrap(self, fn: Any) -> Any:
        def _wrapped(*a: Any, **kw: Any) -> Any:
            result = fn(*a, **kw)
            self.last = result
            return result
        return _wrapped


def project_calls(result: Any) -> list[dict[str, Any]]:
    """One record per EXECUTED call of ``TOOL`` from ``tool_calls_trace``:
    the args the model sent and the gameweeks the tool described."""
    trace = getattr(result, "tool_calls_trace", None) or ()
    calls: list[dict[str, Any]] = []
    for entry in trace:
        if entry.get("name") != TOOL:
            continue
        args = entry.get("args") or {}
        output = entry.get("output") or {}
        calls.append({
            "round": entry.get("round"),
            "target_gw": args.get("target_gw"),
            "horizon": args.get("horizon"),
            "team_query": args.get("team_query"),
            "axis": args.get("axis"),
            "output_status": output.get("status"),
            "verdict_scope": output.get("verdict_scope"),
            "series_gws": _series_gws(output),
        })
    return calls


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bootstrap", default=str(base.DEFAULT_BOOTSTRAP))
    parser.add_argument("--reps", type=int, default=3)
    parser.add_argument("--out", required=True)
    parser.add_argument("--min-lead", type=int, default=2,
                        help="only phrases whose gameweek is >= current_gw + this (default 2)")
    parser.add_argument("--cap-usd", type=float, default=1.0,
                        help="declared spend cap; abort before the first call if the estimate exceeds it")
    args = parser.parse_args(argv)

    base._configure_imports()
    base._load_env_file(base.PACKAGE_ROOT / ".env")
    api_key = base.require_api_key(base.PROVIDER)

    from tool_routing_corpus import (  # noqa: PLC0415
        I78A_CANONICAL_PHRASES_PATH,
        i101_target_gw_corpus,
    )
    from fpl_api_client import get_current_gameweek  # noqa: PLC0415
    from fpl_grounded_assistant import orchestrator as orch_mod  # noqa: PLC0415
    from fpl_grounded_assistant.tool_schema_registry import get_tool_schema  # noqa: PLC0415

    bootstrap = json.loads(Path(args.bootstrap).read_text(encoding="utf-8"))
    current_gw = get_current_gameweek(bootstrap)
    if current_gw is None:
        print("bootstrap has no current/next gameweek; cannot compute leads", file=sys.stderr)
        return 1
    questions = i101_target_gw_corpus(current_gw, min_lead=args.min_lead)
    if not questions:
        print("no phrase is far enough ahead of the bootstrap's current GW", file=sys.stderr)
        return 1

    schema = get_tool_schema(TOOL)
    corpus_sha = {
        "i78a_canonical_phrases_json": _sha256(I78A_CANONICAL_PHRASES_PATH),
        "tool_routing_corpus_py": _sha256(SCRIPTS_DIR / "tool_routing_corpus.py"),
        "description": hashlib.sha256((schema.description if schema else "").encode("utf-8")).hexdigest()[:16],
        "schema_has_target_gw": bool(schema and "target_gw" in schema.parameters.get("properties", {})),
    }
    total_calls = len(questions) * args.reps
    estimate = _estimate_usd(total_calls)
    print(
        f"corpus: {len(questions)} phrases (current_gw={current_gw}, lead>={args.min_lead}, "
        f"gws={sorted({q['i101']['expected_target_gw'] for q in questions})}) x {args.reps} reps "
        f"= {total_calls} calls against {base.PROVIDER}/{base.MODEL}",
        file=sys.stderr,
    )
    print(f"corpus sha256: {json.dumps(corpus_sha)}", file=sys.stderr)
    print(f"estimated spend: ${estimate:.3f} (cap ${args.cap_usd:.2f})", file=sys.stderr)
    if estimate > args.cap_usd:
        print("estimate exceeds the declared cap; reduce --reps or the corpus. No call made.",
              file=sys.stderr)
        return 2

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    capture = _ResultCapture()
    original = orch_mod.ask_orchestrated
    orch_mod.ask_orchestrated = capture.wrap(original)
    n_done = n_exc = 0
    written: list[dict[str, Any]] = []
    try:
        with out_path.open("a", encoding="utf-8") as fh:
            for q in questions:
                for rep in range(args.reps):
                    capture.last = None
                    obs = base.run_one(q, rep, bootstrap, api_key)
                    obs["i78a"] = q.get("i78a")
                    obs["i101"] = dict(q["i101"])
                    obs["i101"]["calls"] = project_calls(capture.last) if capture.last is not None else []
                    obs["forbidden_tools"] = list(q.get("forbidden_tools") or [])
                    obs["corpus_sha256"] = corpus_sha
                    fh.write(json.dumps(obs, ensure_ascii=False) + "\n")
                    fh.flush()
                    written.append(obs)
                    n_done += 1
                    if obs["exception"] is not None:
                        n_exc += 1
                    if n_done % 12 == 0 or n_done == total_calls:
                        print(f"  {n_done}/{total_calls} done, {n_exc} exceptions, "
                              f"{base.format_spend(written)} so far", file=sys.stderr)
    finally:
        orch_mod.ask_orchestrated = original

    print(f"DONE. {n_done} observations -> {out_path}, {n_exc} exceptions, "
          f"spend {base.format_spend(written)}", file=sys.stderr)
    return 0 if n_exc == 0 else 3


if __name__ == "__main__":
    raise SystemExit(main())
